# Generated by Django 5.1.6 on 2025-02-27 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_name', models.CharField(max_length=200)),
                ('intake_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
            ],
            options={
                'ordering': ['-intake_datetime'],
            },
        ),
    ]
